import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";

// Optional imports - will use fallback if not available
let Docx: any;
let PDFDocument: any;
let XLSX: any;

try {
  Docx = require("docx");
} catch {
  console.log("docx package not available, using text fallback");
}

try {
  XLSX = require("xlsx");
} catch {
  console.log("xlsx package not available, using CSV fallback");
}

export async function POST(request: NextRequest) {
  try {
    const { workspace } = await request.json();

    if (!workspace) {
      return NextResponse.json({ error: "No workspace data provided" }, { status: 400 });
    }

    const zip = new JSZip();

    // Generate SF-424 PDF (or text fallback)
    const sf424Content = generateSF424Content(workspace);
    zip.file("SF-424.txt", sf424Content);

    // Generate Project Narrative DOCX (or text fallback)
    if (Docx) {
      const narrativeBuffer = await generateDocxNarrative(workspace);
      zip.file("Project_Narrative.docx", narrativeBuffer);
    } else {
      zip.file("Project_Narrative.txt", workspace.projectNarrative || "No narrative provided");
    }

    // Generate Budget XLSX (or CSV fallback)
    const budgetContent = generateBudgetContent(workspace);
    if (XLSX) {
      const budgetBuffer = generateXlsxBudget(workspace);
      zip.file("Budget_Summary.xlsx", budgetBuffer);
    } else {
      zip.file("Budget_Summary.csv", budgetContent);
    }

    // Generate Compliance Checklist
    const checklistContent = generateChecklistContent(workspace);
    zip.file("Compliance_Checklist.txt", checklistContent);

    // Generate README
    const readme = generateReadme(workspace);
    zip.file("README.txt", readme);

    const zipArrayBuffer = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(zipArrayBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="fedsignal-package-${workspace.opportunityId || "proposal"}.zip"`,
      },
    });
  } catch (error) {
    console.error("Package generation error:", error);
    return NextResponse.json(
      { error: "Failed to generate package", details: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    );
  }
}

function generateSF424Content(workspace: any): string {
  const sf = workspace.sf424 || {};
  return `
================================================================================
                    SF-424 APPLICATION FOR FEDERAL ASSISTANCE
================================================================================

Generated by FedSignal on ${new Date().toLocaleDateString()}

--------------------------------------------------------------------------------
SECTION A: APPLICANT INFORMATION
--------------------------------------------------------------------------------

Legal Name:                 ${sf.legalName || "[NOT PROVIDED]"}
Employer ID/TIN (EIN):        ${sf.ein || "[NOT PROVIDED]"}
DUNS Number:                ${sf.duns || "[NOT PROVIDED]"}

Address:                    ${sf.address || "[NOT PROVIDED]"}
City:                       ${sf.city || "[NOT PROVIDED]"}
State:                      ${sf.state || "[NOT PROVIDED]"}
Zip Code:                   ${sf.zip || "[NOT PROVIDED]"}
Congressional District:     ${sf.congressionalDistrict || "[NOT PROVIDED]"}

--------------------------------------------------------------------------------
SECTION B: PROJECT INFORMATION
--------------------------------------------------------------------------------

Federal Agency:             ${workspace.agency || "[NOT PROVIDED]"}
Federal Identifier:         ${workspace.solicitationNumber || "[NOT PROVIDED]"}

Project Title:              ${sf.projectTitle || workspace.title || "[NOT PROVIDED]"}
Proposed Amount:            $${sf.proposedAmount || "[NOT PROVIDED]"}
Project Duration:           ${sf.projectDuration || "[NOT PROVIDED]"} months

Project Director:           ${sf.projectDirector || "[NOT PROVIDED]"}
Phone:                      ${sf.phone || "[NOT PROVIDED]"}
Email:                      ${sf.email || "[NOT PROVIDED]"}

--------------------------------------------------------------------------------
SECTION C: BUDGET SUMMARY
--------------------------------------------------------------------------------

Direct Costs:               $${parseFloat(workspace.budgetSummary?.directCosts || "0").toLocaleString()}
Indirect Costs (F&A):       $${parseFloat(workspace.budgetSummary?.indirectCosts || "0").toLocaleString()}
TOTAL PROJECT COST:         $${parseFloat(workspace.budgetSummary?.totalCosts || "0").toLocaleString()}

--------------------------------------------------------------------------------
SECTION D: ASSURANCES
--------------------------------------------------------------------------------

The applicant certifies that:
- All information is true and accurate
- Applicant has authority to apply
- Project complies with federal regulations

================================================================================
                              END OF SF-424
================================================================================
`.trim();
}

async function generateDocxNarrative(workspace: any): Promise<Buffer> {
  if (!Docx) {
    return Buffer.from(workspace.projectNarrative || "No narrative provided");
  }

  const {
    Document,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
    Packer,
  } = Docx;

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: workspace.sf424?.projectTitle || workspace.title || "Project Narrative",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Agency: ${workspace.agency || "N/A"}`,
                bold: true,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Solicitation: ${workspace.solicitationNumber || "N/A"}`,
                bold: true,
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Budget: $${parseFloat(workspace.budgetSummary?.totalCosts || "0").toLocaleString()}`,
                bold: true,
              }),
            ],
          }),
          new Paragraph({
            text: "",
          }),
          new Paragraph({
            text: "PROJECT NARRATIVE",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: workspace.projectNarrative || "No project narrative provided.",
          }),
          new Paragraph({
            text: "",
          }),
          new Paragraph({
            text: "ABSTRACT",
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: workspace.abstract || "No abstract provided.",
          }),
          new Paragraph({
            text: "",
          }),
          new Paragraph({
            text: "KEY PERSONNEL",
            heading: HeadingLevel.HEADING_1,
          }),
          ...(workspace.keyPersonnel?.length
            ? workspace.keyPersonnel.map((person: string) => new Paragraph({ text: `• ${person}` }))
            : [new Paragraph({ text: "No key personnel listed." })]),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return buffer;
}

function generateBudgetContent(workspace: any): string {
  const bs = workspace.budgetSummary || {};
  return `Budget Summary
Generated by FedSignal

Direct Costs,${parseFloat(bs.directCosts || "0").toFixed(2)}
Indirect Costs (F&A @ 55%),${parseFloat(bs.indirectCosts || "0").toFixed(2)}
TOTAL PROJECT COST,${parseFloat(bs.totalCosts || "0").toFixed(2)}

Note: F&A rate calculated at 55%. Adjust as per your institution's negotiated rate.
`;
}

function generateXlsxBudget(workspace: any): Buffer {
  if (!XLSX) {
    return Buffer.from(generateBudgetContent(workspace));
  }

  const bs = workspace.budgetSummary || {};
  const data = [
    ["FedSignal Budget Summary"],
    ["Generated:", new Date().toLocaleDateString()],
    [],
    ["Category", "Amount"],
    ["Direct Costs", parseFloat(bs.directCosts || "0")],
    ["Indirect Costs (F&A @ 55%)", parseFloat(bs.indirectCosts || "0")],
    ["TOTAL PROJECT COST", parseFloat(bs.totalCosts || "0")],
    [],
    ["Opportunity:", workspace.title || "N/A"],
    ["Agency:", workspace.agency || "N/A"],
    ["Solicitation:", workspace.solicitationNumber || "N/A"],
  ];

  const ws = XLSX.utils.aoa_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Budget Summary");

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
}

function generateChecklistContent(workspace: any): string {
  const checklist = workspace.checklist || {};
  const items = [
    { id: "sf424-complete", label: "SF-424 form completed" },
    { id: "narrative-draft", label: "Project narrative drafted" },
    { id: "budget-complete", label: "Budget summary with F&A calculated" },
    { id: "personnel-confirmed", label: "Key personnel bios attached" },
    { id: "budget-totals-match", label: "Budget totals match narrative" },
    { id: "deadline-valid", label: "Deadline not passed" },
    { id: "hbcu-eligible", label: "HBCU set-aside eligibility confirmed" },
    { id: "subk-plan", label: "Sub-contracting plan (if required)" },
  ];

  return `
================================================================================
                    FEDSIGNAL COMPLIANCE CHECKLIST
================================================================================

Generated: ${new Date().toLocaleString()}
Opportunity: ${workspace.title || "N/A"}
Agency: ${workspace.agency || "N/A"}

--------------------------------------------------------------------------------
CHECKLIST ITEMS
--------------------------------------------------------------------------------

${items
  .map((item) => `[${checklist[item.id] ? "X" : " "}] ${item.label}`)
  .join("\n")}

--------------------------------------------------------------------------------
STATUS SUMMARY
--------------------------------------------------------------------------------

Required Items Passed: ${items.filter((i) => i.id !== "hbcu-eligible" && i.id !== "subk-plan" && checklist[i.id]).length} / 6
Optional Items Passed: ${items.filter((i) => (i.id === "hbcu-eligible" || i.id === "subk-plan") && checklist[i.id]).length} / 2

Overall Status: ${items.filter((i) => i.id !== "hbcu-eligible" && i.id !== "subk-plan").every((i) => checklist[i.id]) ? "READY FOR SUBMISSION" : "INCOMPLETE - DO NOT SUBMIT"}

================================================================================
                              END OF CHECKLIST
================================================================================
`.trim();
}

function generateReadme(workspace: any): string {
  return `
FEDSIGNAL SUBMISSION PACKAGE
================================================================================

This package was generated by FedSignal on ${new Date().toLocaleString()}.

CONTENTS:
---------
1. SF-424.txt          - Federal application form (pre-filled)
2. Project_Narrative   - Your proposal narrative document
3. Budget_Summary      - Budget with F&A calculations
4. Compliance_Checklist - Audit trail of your compliance checks

NEXT STEPS:
-----------
1. Review all documents carefully
2. Save SF-424.txt as PDF or upload to Grants.gov
3. Copy narrative into the agency's submission portal
4. Upload budget spreadsheet if required
5. Submit before deadline: ${workspace.deadline || "Check opportunity page"}

IMPORTANT NOTES:
----------------
- This is a pre-filled draft. Always review before submission.
- Verify your institution's F&A rate matches the 55% default used here.
- Confirm all key personnel are available for the project duration.
- Check Grants.gov for any additional forms required by this agency.

SUPPORT:
--------
- FedSignal Pipeline: /fedsignal/pipeline
- Grant Tracker: /fedsignal/grants
- Hermes AI Assistant: Click "Ask Hermes" in the sidebar

================================================================================
`.trim();
}
